### ISSUE TITLE
Link in README.md gives 404

### ISSUE THREAD

**Issue by VonUniGE** [dbmdz/iiif-image-api#5]
In the section Configuration of the README.md file, the url:
```
 https://github.com/dbmdz/digitalcollections-core/tree/master/digitalcollections-core-backend/digitalcollections-core-backend-impl-file
```
gives 404.

**Comment by morpheus-87** [comment]
Thanks for this issue, I fixed the link.

However, this library will be deprecated in the future in favor of a library implementing the complete specification: https://github.com/dbmdz/iiif-apis

**Comment by VonUniGE** [comment]
Thank you for the information, I would like to run an iiif server under spring boot for production use. Which is, in your opinion, the best project to start with?

**Comment by morpheus-87** [comment]
[Hymir](https://github.com/dbmdz/iiif-server-hymir) is our IIIF server, it's based on Spring Boot. At the moment, it still uses the "old" image and presentation api libraries - but in the future, we will replace them by the new library I mentioned above.
